### ISSUE TITLE
Upload trained models

### ISSUE THREAD

**Issue by zwshan** [marcpaga/basecalling_architectures#1]
Could you please upload the trained models on the github or send them to me?

**Comment by zwshan** [comment]
I will cite your paper and appreciate you.

**Comment by marcpaga** [comment]
Hi @zwshan, thanks for your interest in the models.

I have uploaded all the models we trained to surfdrive (about 10Gb download), here's the link: https://surfdrive.surf.nl/files/index.php/s/bqbYOjcSBKRIOZB

If this works for you, please close the issue.

**Comment by zwshan** [comment]
thank you, it works for me well.
Thank you for your work!
If I can work out a paper, I will cite your paper and appreciate you!

**Comment by TiloccaS** [comment]
Hi @marcpaga,
I noticed that the model working with Bonito when using the default parameters is Bonito Recreation.
Are the performance metrics for this model reported in the paper? I ask because its results seem to differ from all the other bonito models shown in the grid analysis.

**Comment by marcpaga** [comment]
No, this model is specific for the Comparison of original models to model recreations methods section.

**Comment by TiloccaS** [comment]
So, the GitHub repository code doesn’t include the different Bonito variants, like Bonito FWD, Bonito LSTM5, etc.?

**Comment by marcpaga** [comment]
It does: https://github.com/marcpaga/basecalling_architectures/blob/main/scripts/train_comb.py
