### ISSUE TITLE
Working on the Bonito model

### ISSUE THREAD

**Issue by srrmtt** [marcpaga/basecalling_architectures#3]
Hi @marcpaga , thanks for your work,  we are a research group that is currently working on the bonito architecture, I have some questions for you:

-  we are trying to replicate the paper results with the Bonito architecture, can you provide us the parameters used for training the model (or if you please directly the command) and if you used the `train_original.py`  or the `train_grid_recurrent.py` script?
-  if we want to test the basecalling on the whole dataset, do we have to create a single folder with the fasq and fast5 files or there is a way to evalaute it on the whole dataset but using different folders? 
- To finish, to basecall with bonito do we have to use the `basecalling.py` script or the `grid_recurrent` one?

Thanks in adavnce, best regards

**Comment by marcpaga** [comment]
- To replicate the Bonito model use `train_original.py` with default values and `--window-size 2000`.

- The scripts do not search recursively or accept multiple arguments, so all the files should be in the same folder. However, you can change this if you want, here for example (https://github.com/marcpaga/basecalling_architectures/blob/14e041272e9fd7774f65b5023da2e687bc2f1d46/scripts/basecall_original.py#L42). `file_list` contains a list of fast5 files to be basecalled, you can modify that to the list of files that you want to basecall.

- To basecall with bonito use the `basecall_original.py` script.
