### ISSUE TITLE
No training occurs with demo data

### ISSUE THREAD

**Issue by shishir-reddy** [marcpaga/basecalling_architectures#5]
Hi, I am trying to test the train_comb.py script with the resquiggled, chunked demo data provided but I am running into an issue where the training loop never starts.

After debugging the training loop, the [loader_train dataset](https://github.com/marcpaga/basecalling_architectures/blob/f8686069c3021304aac03bf99bdb07849911ab00/scripts/train_comb.py#L98-L99) is empty when running the script so it looks like the input files are not being parsed correctly on my end. Are you able to reproduce this error? Thanks in advance for the help!

**Comment by marcpaga** [comment]
Can you provide how did you exactly run the script?

**Comment by marcpaga** [comment]
I think I found the problem: since there's only a single file, when splitting training and validation data that single file is assigned to validation data, and therefore there's no training data. 
Can you duplicate the demo file (`cp data_0.npz data_1.npz`) and try again?

**Comment by shishir-reddy** [comment]
This fixes the problem for me, thanks!
