### ISSUE TITLE
Fully trained checkpoints available?

### ISSUE THREAD

**Issue by maximilianmordig** [marcpaga/basecalling_architectures#8]
Are the checkpoints for the fully trained models available?
Or do I have to download the data from https://github.com/marcpaga/nanopore_benchmark and train it myself?

The repo contains https://github.com/marcpaga/basecalling_architectures/tree/main/demo_data/properly_trained_bonito, but I am wondering about the other models you trained for your paper.

**Comment by marcpaga** [comment]
See this for the checkpoints: https://github.com/marcpaga/basecalling_architectures/issues/1
